version: '3'

services:
  app:
    build: 
      context: .
    ports:
       - "80:5000"
    env_file:
      - ./.prod_env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev
volumes:
  postgres_data:

